/**
 * GENERATED by scripts/i18n/generate.mjs — do not edit by hand.
 *
 * Regenerate with `node scripts/i18n/generate.mjs`; CI rejects drift
 * (`node scripts/i18n/generate.mjs --check`), which re-generates in memory and
 * requires byte-identical output.
 *
 * Two halves, both derived from `src/i18n/catalogues/en/*.json`:
 *
 * - `MessageParams` — the typed key map RFC §2.4 proved: one entry per bundled
 *   message id, its parameter shape inferred from the message's own ICU
 *   placeholders. `t()` in `./messages.ts` is declared against these types, so
 *   a mistyped key or a wrong parameter value fails `tsc`.
 * - `bundledEnglish` — the flat en message map `t()` falls back to (RFC §2.1:
 *   a client bundles its own namespaces and a bootstrap set; the served
 *   `wire.*` catalogues layer on top of it at runtime).
 *
 * The context sidecars (`*.context.json`) are deliberately NOT inputs: they
 * describe keys for translators (§2.2), and a key must exist in the message
 * file itself to be part of the contract.
 */

import uiAgents from "./catalogues/en/ui.agents.json";
import uiBrowser from "./catalogues/en/ui.browser.json";
import uiChat from "./catalogues/en/ui.chat.json";
import uiConsole from "./catalogues/en/ui.console.json";
import uiHub from "./catalogues/en/ui.hub.json";
import uiMesh from "./catalogues/en/ui.mesh.json";
import uiOnboarding from "./catalogues/en/ui.onboarding.json";
import uiProjects from "./catalogues/en/ui.projects.json";
import uiProviders from "./catalogues/en/ui.providers.json";
import uiSchedules from "./catalogues/en/ui.schedules.json";
import uiSettings from "./catalogues/en/ui.settings.json";
import uiShell from "./catalogues/en/ui.shell.json";

/** The bundled en catalogue: every `src/i18n/catalogues/en` message, flat. */
export const bundledEnglish: Readonly<Record<string, string>> = {
	...uiAgents,
	...uiBrowser,
	...uiChat,
	...uiConsole,
	...uiHub,
	...uiMesh,
	...uiOnboarding,
	...uiProjects,
	...uiProviders,
	...uiSchedules,
	...uiSettings,
	...uiShell,
};

/** One entry per bundled message id, shaped by the message's own arguments. */
export type MessageParams = Record<never, never>;

export type MessageKey = keyof MessageParams;

/** Keys whose message carries at least one argument (RFC §2.4). */
export type WithParams = {
	[K in MessageKey]: MessageParams[K] extends undefined ? never : K;
}[MessageKey];

/** Keys whose message is complete on its own (RFC §2.4). */
export type WithoutParams = {
	[K in MessageKey]: MessageParams[K] extends undefined ? K : never;
}[MessageKey];
