#!/usr/bin/env node
/**
 * Regenerate `src/i18n/keys.gen.ts` from the en catalogues, or check it for drift.
 *
 * WHAT THIS OWNS (generated-but-committed, so the drift check is the contract):
 *
 * - `MessageParams` — the typed key map RFC §2.4 proved with a spike: one entry
 *   per bundled message id, with the parameter shape inferred from the message's
 *   own ICU placeholders (`{count, plural, …}` -> `number`, `{when, date}` ->
 *   `Date | number`, `{name}` / `{choice, select}` -> `string`).
 * - `bundledEnglish` — the flat en message map `t()` falls back to (RFC §2.1:
 *   every client bundles its own namespaces; the served `wire.*` catalogues
 *   layer on top of this at runtime).
 * - `MessageKey` / `WithParams` / `WithoutParams` — the type algebra the
 *   two-overload `t()` in `src/i18n/messages.ts` is declared against. That
 *   overload shape is the one the RFC's spike measured rejecting all four
 *   negative cases, and §2.4 records the spike measuring a conditional-tuple
 *   signature (`(...args: Params extends undefined ? [] : [p: Params])`)
 *   ACCEPTING a missing params object — the reason the shape stays two
 *   overloads. Round-1 review (R1-4) re-measured the swap and it rejected all
 *   four cases as re-tried here anyway, so the choice rests on §2.4's spike:
 *   `scripts/i18n/typed-keys.test.mjs` pins only the SHIPPED shape's four
 *   rejections and does not claim the swap fails it.
 *
 * WHY A DRIFT CHECK. A catalogue change without regeneration would ship types
 * that disagree with the messages, so `--check` re-generates in memory and
 * requires byte-identical output. WHERE IT RUNS (round-1 review, R1-2 — there
 * is no separate CI job): a case in `scripts/i18n/typed-keys.test.mjs` invokes
 * `--check`, and that suite is part of `test:desktop`, which CI executes for
 * every change to this directory; `pnpm check-i18n` chains `--check` ahead of
 * the string scanner as the one-command local gate.
 *
 * DETERMINISM RULES, all load-bearing for that byte-comparison: no clock reads,
 * no environment reads, sorted iteration everywhere (files, and keys within
 * each file), LF newlines, one trailing newline, and output that satisfies
 * `biome check` AS GENERATED — the check compares bytes, so a formatter pass
 * after generation would make the check unreproducible.
 *
 * USAGE:
 *   node scripts/i18n/generate.mjs            # write src/i18n/keys.gen.ts
 *   node scripts/i18n/generate.mjs --check    # verify only; exit 1 on drift
 *   node scripts/i18n/generate.mjs --catalogues <dir> --out <file>   # fixtures
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { TYPE, parse } from "@formatjs/icu-messageformat-parser";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

/** The generated module's header. Kept out of the body so both readers see one copy. */
const HEADER = `/**
 * GENERATED by scripts/i18n/generate.mjs — do not edit by hand.
 *
 * Regenerate with \`node scripts/i18n/generate.mjs\`. Drift fails the desktop
 * suite, which CI runs: \`scripts/i18n/typed-keys.test.mjs\` invokes
 * \`--check\`, re-generating in memory and requiring byte-identical output
 * (round-1 review, R1-2).
 *
 * Two halves, both derived from \`src/i18n/catalogues/en/*.json\`:
 *
 * - \`MessageParams\` — the typed key map RFC §2.4 proved: one entry per bundled
 *   message id, its parameter shape inferred from the message's own ICU
 *   placeholders. \`t()\` in \`./messages.ts\` is declared against these types, so
 *   a mistyped key or a wrong parameter value fails \`tsc\`.
 * - \`bundledEnglish\` — the flat en message map \`t()\` falls back to (RFC §2.1:
 *   a client bundles its own namespaces and a bootstrap set; the served
 *   \`wire.*\` catalogues layer on top of it at runtime).
 *
 * The context sidecars (\`*.context.json\`) are deliberately NOT inputs: they
 * describe keys for translators (§2.2), and a key must exist in the message
 * file itself to be part of the contract.
 */
`;

/** TS annotation per placeholder kind — the map the RFC's spike exercised. */
const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const WORD_SPLIT_RE = /[^A-Za-z0-9]+/;

const TYPE_BY_KIND = {
	argument: "string",
	number: "number",
	plural: "number",
	select: "string",
	date: "Date | number",
	time: "Date | number",
};

/**
 * `(name, annotation)` per argument of `message`, first-appearance order.
 *
 * Nested branches are walked (a `{n, plural, …}` body may itself interpolate
 * other arguments), mirroring `message_arguments` in the core runtime so both
 * generators type the same catalogue identically. First appearance wins: a
 * message that re-uses a name gets one entry with the first kind seen.
 */
export function messageArguments(message) {
	const seen = new Map();
	const walk = (nodes) => {
		for (const node of nodes) {
			let annotation = TYPE_BY_KIND.argument;
			const kind =
				node.type === TYPE.number
					? "number"
					: node.type === TYPE.plural
						? "plural"
						: node.type === TYPE.select
							? "select"
							: node.type === TYPE.date
								? "date"
								: node.type === TYPE.time
									? "time"
									: "argument";
			if (kind !== "argument" || node.type === TYPE.argument) {
				annotation = TYPE_BY_KIND[kind] ?? "string";
			}
			if (
				node.type === TYPE.argument ||
				node.type === TYPE.number ||
				node.type === TYPE.plural ||
				node.type === TYPE.select ||
				node.type === TYPE.date ||
				node.type === TYPE.time
			) {
				if (!seen.has(node.value)) seen.set(node.value, annotation);
			}
			if (
				node.type === TYPE.plural ||
				node.type === TYPE.select ||
				node.type === TYPE.tag
			) {
				for (const option of Object.values(node.options ?? {})) {
					if (Array.isArray(option?.value)) walk(option.value);
				}
			}
		}
	};
	walk(parse(message));
	return [...seen.entries()];
}

/** A TS parameter name: bare for identifiers, quoted for anything else. */
function parameterKey(name) {
	return IDENTIFIER_RE.test(name) ? name : JSON.stringify(name);
}

/** A message id as an object-type key. Keys are dotted, so always quoted. */
function messageKey(key) {
	return JSON.stringify(key);
}

/**
 * Every en catalogue's messages, as `{ namespace, key, message }` triples in a
 * deterministic order. Refuses the shapes a later slice would otherwise debug
 * from a wrong render: a non-string message, and one key defined twice across
 * files (the §2.2 collision rule — the key would silently shadow).
 */
export function readCatalogues(cataloguesDir) {
	const enDir = join(cataloguesDir, "en");
	const files = readdirSync(enDir)
		.filter((name) => name.endsWith(".json") && !name.endsWith(".context.json"))
		.sort();
	const entries = [];
	const owner = new Map();
	for (const file of files) {
		const namespace = file.slice(0, -".json".length);
		const data = JSON.parse(readFileSync(join(enDir, file), "utf8"));
		for (const key of Object.keys(data).sort()) {
			const message = data[key];
			if (typeof message !== "string") {
				throw new Error(
					`${file}: ${key} is not a message string (got ${typeof message})`,
				);
			}
			const previous = owner.get(key);
			if (previous !== undefined) {
				throw new Error(
					`duplicate key ${key}: defined by both ${previous} and ${file} — one key belongs to exactly one namespace file (RFC §2.2)`,
				);
			}
			owner.set(key, file);
			entries.push({ namespace, file, key, message });
		}
	}
	return { files, entries };
}

/** The full `keys.gen.ts` text for `entries`, byte-stable for a given input. */
export function renderKeysModule(cataloguesDir) {
	const { files, entries } = readCatalogues(cataloguesDir);

	const imports = files
		.map((file) => {
			const namespace = file.slice(0, -".json".length);
			const identifier = namespace
				.split(WORD_SPLIT_RE)
				.filter(Boolean)
				.map((part, index) =>
					index === 0
						? part.charAt(0).toLowerCase() + part.slice(1)
						: part.charAt(0).toUpperCase() + part.slice(1),
				)
				.join("");
			return {
				file,
				identifier,
				line: `import ${identifier} from "./catalogues/en/${file}";`,
			};
		})
		.sort((a, b) => (a.file < b.file ? -1 : a.file > b.file ? 1 : 0));

	const spread = imports.map((entry) => `\t...${entry.identifier},`).join("\n");

	const members = [];
	for (const entry of entries) {
		const args = messageArguments(entry.message);
		if (args.length === 0) {
			members.push(`\t${messageKey(entry.key)}: undefined;`);
		} else {
			const shape = args
				.map(([name, annotation]) => `${parameterKey(name)}: ${annotation}`)
				.join("; ");
			members.push(`\t${messageKey(entry.key)}: { ${shape} };`);
		}
	}

	/*
	 * A TYPE ALIAS, not an interface, and ONE spelling per state, because the
	 * drift check compares BYTES: the emitted text must be what `biome check src`
	 * leaves standing. An empty interface is `noEmptyInterface` to biome (its own
	 * suggested fix is the alias); a bare empty `{}` type is `noBannedTypes`; so
	 * the empty state is spelled `Record<never, never>` (a map with no keys —
	 * `keyof` still collapses to `never`, which is what the no-keys state means).
	 * The RFC spells the map as an interface; the alias is the same type, and
	 * `scripts/i18n/typed-keys.test.mjs` pins the four negative cases against
	 * THIS spelling.
	 */
	const map = members.length
		? ["export type MessageParams = {", ...members, "};"]
		: ["export type MessageParams = Record<never, never>;"];

	return [
		HEADER,
		imports.map((entry) => entry.line).join("\n"),
		"",
		"/** The bundled en catalogue: every `src/i18n/catalogues/en` message, flat. */",
		"export const bundledEnglish: Readonly<Record<string, string>> = {",
		spread,
		"};",
		"",
		"/** One entry per bundled message id, shaped by the message's own arguments. */",
		...map,
		"",
		"export type MessageKey = keyof MessageParams;",
		"",
		"/** Keys whose message carries at least one argument (RFC §2.4). */",
		"export type WithParams = {",
		"\t[K in MessageKey]: MessageParams[K] extends undefined ? never : K;",
		"}[MessageKey];",
		"",
		"/** Keys whose message is complete on its own (RFC §2.4). */",
		"export type WithoutParams = {",
		"\t[K in MessageKey]: MessageParams[K] extends undefined ? K : never;",
		"}[MessageKey];",
		"",
	].join("\n");
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

export function main(argv) {
	let check = false;
	let cataloguesDir = join(REPO, "src", "i18n", "catalogues");
	let outFile = join(REPO, "src", "i18n", "keys.gen.ts");
	for (let index = 0; index < argv.length; index += 1) {
		const arg = argv[index];
		if (arg === "--check") check = true;
		else if (arg === "--catalogues") cataloguesDir = resolve(argv[++index]);
		else if (arg === "--out") outFile = resolve(argv[++index]);
		else if (arg === "--help" || arg === "-h") {
			process.stdout.write(
				"usage: node scripts/i18n/generate.mjs [--check] [--catalogues <dir>] [--out <file>]\n",
			);
			return 0;
		} else {
			process.stderr.write(`generate.mjs: unknown argument ${arg}\n`);
			return 2;
		}
	}
	let rendered;
	try {
		rendered = renderKeysModule(cataloguesDir);
	} catch (error) {
		process.stderr.write(`generate.mjs: ${error.message}\n`);
		return 1;
	}
	if (check) {
		let current = null;
		try {
			current = readFileSync(outFile, "utf8");
		} catch {
			// Missing output is drift like any other: the check below prints it.
		}
		if (current === rendered) {
			process.stdout.write(
				`${outFile} is byte-identical to a fresh generation.\n`,
			);
			return 0;
		}
		process.stderr.write(
			`generate.mjs: ${outFile} is stale — re-run \`node scripts/i18n/generate.mjs\` and commit the result\n`,
		);
		return 1;
	}
	writeFileSync(outFile, rendered);
	process.stdout.write(`wrote ${outFile}\n`);
	return 0;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	process.exitCode = main(process.argv.slice(2));
}
